 SUBROUTINE EosLoadIAPWSScalars(ttrip, ptrip, vtrip, &
 tcrit, pcrit, vcrit, tmin, pmin, tmax, pmax, &
 ptable1, ltable1, ntable1, stable1, ptable2, ltable2, ntable2, stable2, &
 ptable3, ltable3, ntable3, stable3, ptable4, ltable4, ntable4, stable4, &
 ptable5, ltable5, ntable5, stable5, ptable6, ltable6, ntable6, stable6, &
 ptable7, ltable7, ntable7, stable7, ptable8, ltable8, ntable8, stable8, &
 ptable9, ltable9, ntable9, stable9, ptable10, ltable10, ntable10, stable10, &
 ntemp, npres, nsubcrittemp, nsupcrittemp, nsattemp, ofirstsattemp, &
 olastsattemp, otemptrip1, otempcrit1, nsubcritpres, nsupcritpres, &
 nsatpres, ofirstsatpres, olastsatpres, oprestrip2, oprescrit2, &
 ofirstsupcritpres, olastsupcritpres, ntot, record)
!
    USE EosIAPWSData, ONLY: SetCritPointIAPWS
    USE IntrType, ONLY: sdk, sik
!
    IMPLICIT NONE
!
!   This routine was generated by the GenSteamTableRoutines program.
!   This routine loads the scalars for the ascii steam table.
!   This source file is based on the steam table with the following header:
! tpfh2ogibb version 1.0, tables of thermodynamic properties of light wate
! generated on 28-Nov-07 at 11:17:19 by stgh2onew  1.0 (1/Mar/01)
!
      CHARACTER(LEN=80), DIMENSION(2), INTENT(OUT) :: record
!
      REAL(sdk), INTENT(OUT) :: ttrip
      REAL(sdk), INTENT(OUT) :: ptrip
      REAL(sdk), INTENT(OUT) :: vtrip
      REAL(sdk), INTENT(OUT) :: tcrit
      REAL(sdk), INTENT(OUT) :: pcrit
      REAL(sdk), INTENT(OUT) :: vcrit
      REAL(sdk), INTENT(OUT) :: tmin
      REAL(sdk), INTENT(OUT) :: tmax
      REAL(sdk), INTENT(OUT) :: pmin
      REAL(sdk), INTENT(OUT) :: pmax
!
      INTEGER(sik), INTENT(OUT) :: ntemp
      INTEGER(sik), INTENT(OUT) :: npres
      INTEGER(sik), INTENT(OUT) :: nsubcrittemp
      INTEGER(sik), INTENT(OUT) :: nsupcrittemp
      INTEGER(sik), INTENT(OUT) :: nsattemp
      INTEGER(sik), INTENT(OUT) :: ofirstsattemp
      INTEGER(sik), INTENT(OUT) :: olastsattemp
      INTEGER(sik), INTENT(OUT) :: otemptrip1
      INTEGER(sik), INTENT(OUT) :: otempcrit1
      INTEGER(sik), INTENT(OUT) :: nsubcritpres
      INTEGER(sik), INTENT(OUT) :: nsupcritpres
      INTEGER(sik), INTENT(OUT) :: nsatpres
      INTEGER(sik), INTENT(OUT) :: ofirstsatpres
      INTEGER(sik), INTENT(OUT) :: olastsatpres
      INTEGER(sik), INTENT(OUT) :: oprestrip2
      INTEGER(sik), INTENT(OUT) :: oprescrit2
      INTEGER(sik), INTENT(OUT) :: ofirstsupcritpres
      INTEGER(sik), INTENT(OUT) :: olastsupcritpres
!
      INTEGER(sik), INTENT(OUT) :: ptable1
      INTEGER(sik), INTENT(OUT) :: ltable1
      INTEGER(sik), INTENT(OUT) :: ntable1
      INTEGER(sik), INTENT(OUT) :: stable1
      INTEGER(sik), INTENT(OUT) :: ptable2
      INTEGER(sik), INTENT(OUT) :: ltable2
      INTEGER(sik), INTENT(OUT) :: ntable2
      INTEGER(sik), INTENT(OUT) :: stable2
      INTEGER(sik), INTENT(OUT) :: ptable3
      INTEGER(sik), INTENT(OUT) :: ltable3
      INTEGER(sik), INTENT(OUT) :: ntable3
      INTEGER(sik), INTENT(OUT) :: stable3
      INTEGER(sik), INTENT(OUT) :: ptable4
      INTEGER(sik), INTENT(OUT) :: ltable4
      INTEGER(sik), INTENT(OUT) :: ntable4
      INTEGER(sik), INTENT(OUT) :: stable4
      INTEGER(sik), INTENT(OUT) :: ptable5
      INTEGER(sik), INTENT(OUT) :: ltable5
      INTEGER(sik), INTENT(OUT) :: ntable5
      INTEGER(sik), INTENT(OUT) :: stable5
      INTEGER(sik), INTENT(OUT) :: ptable6
      INTEGER(sik), INTENT(OUT) :: ltable6
      INTEGER(sik), INTENT(OUT) :: ntable6
      INTEGER(sik), INTENT(OUT) :: stable6
      INTEGER(sik), INTENT(OUT) :: ptable7
      INTEGER(sik), INTENT(OUT) :: ltable7
      INTEGER(sik), INTENT(OUT) :: ntable7
      INTEGER(sik), INTENT(OUT) :: stable7
      INTEGER(sik), INTENT(OUT) :: ptable8
      INTEGER(sik), INTENT(OUT) :: ltable8
      INTEGER(sik), INTENT(OUT) :: ntable8
      INTEGER(sik), INTENT(OUT) :: stable8
      INTEGER(sik), INTENT(OUT) :: ptable9
      INTEGER(sik), INTENT(OUT) :: ltable9
      INTEGER(sik), INTENT(OUT) :: ntable9
      INTEGER(sik), INTENT(OUT) :: stable9
      INTEGER(sik), INTENT(OUT) :: ptable10
      INTEGER(sik), INTENT(OUT) :: ltable10
      INTEGER(sik), INTENT(OUT) :: ntable10
      INTEGER(sik), INTENT(OUT) :: stable10
!
      INTEGER(sik), INTENT(OUT) :: ntot
!
!
!    Load Strings.
      record(1) = 'tpfh2ogibb version 1.0, tables of thermodynamic properties of light wate        '
      record(2) = 'generated on 28-Nov-07 at 11:17:19 by stgh2onew  1.0 (1/Mar/01)                 '
!
!    Load Scalars.
      CALL SetCritPointIAPWS(tcrit, pcrit, vcrit)
      ttrip =   2.731600000000000E+02_sdk
      ptrip =   6.116570000000000E+02_sdk
      vtrip =   1.000351504192709E-03_sdk
      tmin =   1.400000000000000E+02_sdk
      tmax =   6.000000000000000E+03_sdk
      pmin =   1.000000000000000E-03_sdk
      pmax =   9.999999000000000E+07_sdk
!
      ntemp =      157_sik
      npres =      116_sik
      nsubcrittemp =      136_sik
      nsupcrittemp =       22_sik
      nsattemp =      120_sik
      ofirstsattemp =       17_sik
      olastsattemp =      136_sik
      otemptrip1 =       17_sik
      otempcrit1 =      136_sik
      nsubcritpres =      107_sik
      nsupcritpres =       10_sik
      nsatpres =       71_sik
      ofirstsatpres =       37_sik
      olastsatpres =      107_sik
      oprestrip2 =       37_sik
      oprescrit2 =      107_sik
      ofirstsupcritpres =      107_sik
      olastsupcritpres =      116_sik
!
      ptable1 =        0_sik
      ltable1 =      157_sik
      ntable1 =        1_sik
      stable1 =        1_sik
      ptable2 =      157_sik
      ltable2 =      116_sik
      ntable2 =        1_sik
      stable2 =        1_sik
      ptable3 =      273_sik
      ltable3 =    14040_sik
      ntable3 =      117_sik
      stable3 =      117_sik
      ptable4 =    14313_sik
      ltable4 =      639_sik
      ntable4 =        9_sik
      stable4 =        9_sik
      ptable5 =    14952_sik
      ltable5 =   357272_sik
      ntable5 =       37_sik
      stable5 =     5032_sik
      ptable6 =   372224_sik
      ltable6 =   621563_sik
      ntable6 =       37_sik
      stable6 =     5809_sik
      ptable7 =   993787_sik
      ltable7 =    58090_sik
      ntable7 =       37_sik
      stable7 =     5809_sik
      ptable8 =  1051877_sik
      ltable8 =      426_sik
      ntable8 =        6_sik
      stable8 =        6_sik
      ptable9 =  1052303_sik
      ltable9 =      642_sik
      ntable9 =        6_sik
      stable9 =        6_sik
      ptable10 =  1052945_sik
      ltable10 =       60_sik
      ntable10 =        6_sik
      stable10 =        6_sik
!
      ntot =  1053005_sik
!
   END SUBROUTINE EosLoadIAPWSScalars
!
!
