#!/bin/bash

# --- Run from this directory
cd ${0%/*} || exit 1

# --- Initialize the output file
resFile=test.out
rm -rf $resFile
touch $resFile

# --- Run the simulation
echo -e "Run tutorial 1D_PSBT_SC ...\n" | tee -a $resFile
./Allrun >> log.simulation
echo -e "Done running tutorial 1D_PSBT_SC ...\n" | tee -a $resFile

# --- Check it ran
endString=$(tail -3 ./log.GeN-Foam | grep End)
if [ "$endString" = "End" ]; then
    echo -e "1D_PSBT_SC has converged \n" | tee -a $resFile
else
    echo -e "1D_PSBT_SC has NOT converged \n" | tee -a $resFile
    exit 1
fi

# --- Recover the results
input="./0.6/fluidRegion/alpha.vapour"
averageAt=$(head -98 "$input" | tail -1)
expectedAt=0.133727

# --- Check that results are correct
echo "alpha.vapour at the end of the channel" | tee -a $resFile
if [ $averageAt = $expectedAt ]; then
    echo "Perfect match:" | tee -a $resFile
    echo "|              | Simulated | Expected |" | tee -a $resFile
    echo "|:-------------|:---------:|:--------:|" | tee -a $resFile
    echo "| alpha vapour | $averageAt | $expectedAt |" | tee -a $resFile
else
    echo "Divergent results:" | tee -a $resFile
    echo "|              | Simulated | Expected |" | tee -a $resFile
    echo "|:-------------|:---------:|:--------:|" | tee -a $resFile
    echo "| alpha vapour | $averageAt | $expectedAt |" | tee -a $resFile
    exit 1
fi

# --- Exit successfully
exit 0
